version: 0.2

phases:
  pre_build:
    commands:
      - npm install -f
       
  build:
    commands:
        # run build script
        - npm run-script build
     
artifacts:
  files:
    - '**/*'
  base-directory: build
